### ISSUE TITLE
The client secret and default creds are leaked

### ISSUE THREAD

**Issue by yevh** [cloudfoundry/buildpack-acceptance-tests#19]
Hi there,

I found that client secret and default creds are leaked in the following parameters.yml:

https://github.com/cloudfoundry/buildpack-acceptance-tests/blob/master/php/testdata/symfony_2_remote_deps/app/config/parameters.yml

Be secure!

**Comment by robdimsdale** [comment]
Hi @yevh thanks for pointing this out.

However, these secrets are for a temporary app which is temporarily run against localhost for the purposes of testing buildpacks.

As a result, we don't consider this a security issue.

If you disagree, please feel free to re-open this issue and share your reasoning.
